import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { ExportResult } from './exportManager';

export class DownloadManager {
    /**
     * Create a ZIP package of exported files organized by platform
     */
    async createPackage(results: ExportResult[], creativeName: string): Promise<void> {
        const zip = new JSZip();
        const rootFolder = zip.folder(creativeName.replace(/[^a-z0-9]/gi, '_')) || zip;

        // Organize by platform
        results.forEach(result => {
            const platformFolder = rootFolder.folder(result.format.platform);
            if (platformFolder) {
                platformFolder.file(result.filename, result.blob);
            }
        });

        // Add metadata/readme
        const readmeContent = this.generateReadme(results, creativeName);
        rootFolder.file('README.txt', readmeContent);

        // Generate and download
        const content = await zip.generateAsync({ type: 'blob' });
        saveAs(content, `${creativeName}-assets.zip`);
    }

    private generateReadme(results: ExportResult[], creativeName: string): string {
        const date = new Date().toLocaleString();
        return `
# Asset Package: ${creativeName}
Generated on: ${date}

## Contents
${results.map(r => `- ${r.format.platform}/${r.filename} (${r.format.width}x${r.format.height})`).join('\n')}

## Usage Guidelines
- **Facebook/Instagram:** Use .jpg files for feed and stories.
- **LinkedIn:** Use 1200x627 for link posts.
- **Display:** HTML5 or static images as required.

Generated by RetailGen AI
    `.trim();
    }
}

export const downloadManager = new DownloadManager();
