import { ComplianceReport } from './rules';

export interface ComplianceCertificate {
    id: string;
    creativeId: string;
    creativeName: string;
    timestamp: number;
    score: number;
    retailer: string;
    version: string;
    signature: string; // Cryptographic signature for verification
}

export interface AuditLogEntry {
    timestamp: number;
    action: 'check' | 'fix' | 'certify' | 'override';
    userId: string;
    details: any;
}

/**
 * Generate a shareable compliance report
 */
export function generateComplianceReport(
    report: ComplianceReport,
    creativeName: string,
    auditLog: AuditLogEntry[]
): string {
    // In a real app, this would generate a PDF or HTML document
    // For now, we'll return a structured markdown string

    const date = new Date(report.timestamp).toLocaleString();
    const statusIcon = report.overallStatus === 'pass' ? '✅' : report.overallStatus === 'warning' ? '⚠️' : '❌';

    return `
# Compliance Report: ${creativeName}

**Date:** ${date}
**Status:** ${statusIcon} ${report.overallStatus.toUpperCase()}
**Score:** ${report.score}/100

## Summary
- **Total Checks:** ${report.summary.total}
- **Passed:** ${report.summary.passed}
- **Failed:** ${report.summary.failed}
- **Warnings:** ${report.summary.warnings}

## Detailed Results

${report.results.map(r => `
### ${r.passed ? '✅' : r.severity === 'error' ? '❌' : '⚠️'} ${r.ruleName}
- **Status:** ${r.passed ? 'Passed' : 'Failed'}
- **Severity:** ${r.severity}
- **Message:** ${r.message}
${r.suggestion ? `- **Suggestion:** ${r.suggestion}` : ''}
`).join('\n')}

## Audit Trail
${auditLog.map(entry => `
- **${new Date(entry.timestamp).toLocaleTimeString()}** - ${entry.action.toUpperCase()}: ${JSON.stringify(entry.details)}
`).join('\n')}

---
*Generated by RetailGen Compliance Engine*
  `.trim();
}

/**
 * Generate a verification certificate
 */
export function generateCertificate(
    report: ComplianceReport,
    creativeId: string,
    creativeName: string
): ComplianceCertificate {
    if (report.overallStatus === 'fail') {
        throw new Error('Cannot certify non-compliant creative');
    }

    const timestamp = Date.now();
    const signature = btoa(`${creativeId}-${timestamp}-${report.score}-retailgen-verified`);

    return {
        id: `CERT-${timestamp}`,
        creativeId,
        creativeName,
        timestamp,
        score: report.score,
        retailer: 'Tesco', // Default
        version: '1.0',
        signature,
    };
}
